return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 12,
  nextobjectid = 55,
  backgroundcolor = { 0, 0, 0 },
  properties = {
    ["inside"] = true,
    ["music"] = "castletown"
  },
  tilesets = {
    {
      name = "castle_inside",
      firstgid = 1,
      filename = "../tilesets/castle_inside.tsx",
      exportfilename = "../tilesets/castle_inside.lua"
    },
    {
      name = "castle_town_bg",
      firstgid = 129,
      filename = "../tilesets/castle_town_bg.tsx",
      exportfilename = "../tilesets/castle_town_bg.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 12,
      id = 4,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2, 54, 54, 54, 54, 34, 54, 54, 54, 34, 54, 54, 54, 54, 54, 34, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 34, 5, 0,
        0, 0, 3, 54, 34, 54, 54, 54, 54, 54, 54, 6, 54, 54, 54, 54, 34, 54, 6, 54, 54, 54, 34, 54, 54, 54, 54, 54, 54, 54, 5, 0,
        0, 0, 3, 54, 54, 6, 54, 54, 54, 54, 34, 54, 54, 54, 54, 54, 54, 54, 22, 54, 54, 54, 54, 54, 6, 54, 54, 54, 54, 54, 18, 0,
        0, 0, 3, 34, 54, 54, 54, 54, 54, 22, 54, 54, 54, 54, 54, 54, 54, 34, 54, 54, 54, 54, 54, 34, 54, 54, 54, 54, 54, 22, 5, 0,
        0, 0, 19, 20, 20, 20, 20, 20, 20, 20, 36, 20, 20, 20, 20, 36, 20, 20, 20, 20, 20, 20, 20, 20, 36, 20, 20, 20, 20, 20, 21, 0,
        0, 0, 82, 82, 52, 82, 82, 82, 52, 82, 82, 82, 82, 82, 82, 82, 66, 82, 82, 82, 82, 82, 82, 52, 66, 82, 82, 82, 82, 50, 53, 0,
        0, 0, 82, 82, 82, 82, 66, 82, 82, 82, 50, 82, 82, 82, 52, 82, 82, 82, 82, 52, 82, 82, 82, 82, 82, 82, 82, 66, 52, 82, 69, 0,
        0, 0, 82, 50, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 66, 82, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 82, 82, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_decor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512.273,
          y = 281.697,
          width = 106,
          height = 128,
          rotation = 0,
          gid = 175,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 228.242,
          y = 280,
          width = 126,
          height = 184,
          rotation = 0,
          gid = 177,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 310,
          width = 132,
          height = 182,
          rotation = 0,
          gid = 176,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1150,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 32,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1150,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 16,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1110,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 31,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1110,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 15,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1070,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 14,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1070,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 30,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1030,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 29,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1030,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 13,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 990,
          y = 160,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 12,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 990,
          y = 200,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 28,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1030,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 45,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1070,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 46,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1110,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 47,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1110,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 63,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1070,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 62,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1030,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 8,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 480,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "castle_1f",
            ["marker"] = "entry_2f",
            ["sound"] = "escaped"
          }
        },
        {
          id = 10,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 528.273,
          y = 241.697,
          width = 72,
          height = 26,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_delay"] = 0.4,
            ["exit_sound"] = "doorclose",
            ["map"] = "castle_room_kris_susie",
            ["marker"] = "entry_room_kris",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 14,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 254.242,
          y = 234,
          width = 74,
          height = 34,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_delay"] = 0.4,
            ["exit_sound"] = "doorclose",
            ["map"] = "castle_room_kris_susie",
            ["marker"] = "entry_room_susie",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 16,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 806,
          y = 240,
          width = 55,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "castle_room_lancer",
            ["marker"] = "entry",
            ["sound"] = "splat"
          }
        },
        {
          id = 52,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1040,
          y = 240,
          width = 101,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "castle_3f",
            ["marker"] = "spawn",
            ["sound"] = "escaped"
          }
        },
        {
          id = 53,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 253.818,
          y = 266,
          width = 71.4545,
          height = 5.45455,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "susie_room.transition_s"
          }
        },
        {
          id = 54,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 530.364,
          y = 267.273,
          width = 68.9091,
          height = 3.45455,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "kris_room.transition_k"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "entry",
          type = "",
          shape = "point",
          x = 139,
          y = 435,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "spawn",
          type = "",
          shape = "point",
          x = 139,
          y = 355,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "entry_kris",
          type = "",
          shape = "point",
          x = 572.25,
          y = 303.417,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "entry_susie",
          type = "",
          shape = "point",
          x = 289.333,
          y = 304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "entry_lancer",
          type = "",
          shape = "point",
          x = 843,
          y = 304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "entry_3f",
          type = "",
          shape = "point",
          x = 1090,
          y = 304,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 80,
          width = 40,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 360,
          width = 1080,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 80,
          width = 40,
          height = 400,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 80,
          width = 174,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 327,
          y = 80,
          width = 203,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 600,
          y = 80,
          width = 206,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1141,
          y = 80,
          width = 99,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 861,
          y = 80,
          width = 179,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
