return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 23,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 12,
  nextobjectid = 80,
  properties = {
    ["music"] = "castletown"
  },
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../assets/sprites/tilesets/bg_castletown_room_merged.png",
      id = 5,
      name = "bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 505.333,
          y = 142.667,
          width = 70.6667,
          height = 50.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 429.333,
          y = 156,
          width = 54.6667,
          height = 42.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 350.667,
          y = 141.333,
          width = 70.6667,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 244,
          y = 98.6667,
          width = 61.3333,
          height = 105.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 314.667,
          y = 1.33333,
          width = 28,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 125.333,
          height = 480,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 412,
          width = 134.667,
          height = 66.6667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 345.333,
          y = 410.667,
          width = 234.667,
          height = 69.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 669.333,
          y = 410.667,
          width = 250.667,
          height = 69.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 0,
          width = 120,
          height = 409.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 697.333,
          y = 146.667,
          width = 85.3333,
          height = 126.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 153.333,
          width = 81.3333,
          height = 118.333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 605.333,
          y = 140,
          width = 77.3333,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 394.5,
          y = 273.333,
          width = 131.5,
          height = 59.1667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 444.333,
          y = 234.833,
          width = 28.5,
          height = 2.66667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 330.67,
          y = 308.333,
          width = 32,
          height = 15.3334,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 573,
          y = 306.333,
          width = 26.3333,
          height = 15.3333,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 42,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 604.667,
          y = 181.667,
          width = 78.3333,
          height = 14.3333,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 696,
          y = 200,
          width = 87,
          height = 72.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 505,
          y = 167.5,
          width = 71.5,
          height = 26,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 428.5,
          y = 156.5,
          width = 56,
          height = 42,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 349,
          y = 162,
          width = 73,
          height = 33,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 244,
          y = 161,
          width = 62.5,
          height = 43,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 143,
          y = 197.5,
          width = 82.5,
          height = 73.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 262.667,
          y = 473.333,
          width = 75.3333,
          height = 25.3333,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["map"] = "map_castletown_firstfloor",
            ["marker"] = "hall1",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 53,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 588,
          y = 469,
          width = 74,
          height = 25,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["map"] = "map_castletown_firstfloor",
            ["marker"] = "hall2",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 69,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 398.417,
          y = 275.28,
          width = 125.333,
          height = 55.5228,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "room_table.set_table"
          }
        },
        {
          id = 70,
          name = "tea_table",
          type = "",
          shape = "point",
          x = 458.667,
          y = 268,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "npc",
          type = "",
          shape = "point",
          x = 301.333,
          y = 596,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {
            ["actor"] = "ralsei"
          }
        },
        {
          id = 75,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 264,
          y = 449.5,
          width = 73.5,
          height = 11.5,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "room_table.leaving",
            ["once"] = false
          }
        },
        {
          id = 76,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 588.667,
          y = 452,
          width = 74,
          height = 9.33333,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "room_table.leaving",
            ["once"] = false
          }
        },
        {
          id = 77,
          name = "kris_chair",
          type = "",
          shape = "point",
          x = 460.833,
          y = 225,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "ralsei_chair",
          type = "",
          shape = "point",
          x = 346.67,
          y = 292,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "susie_chair",
          type = "",
          shape = "point",
          x = 586,
          y = 294,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2,
          name = "spawn",
          type = "",
          shape = "point",
          x = 673,
          y = 241,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "room1",
          type = "",
          shape = "point",
          x = 300,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "room2",
          type = "",
          shape = "point",
          x = 620,
          y = 440,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
