return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 39,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 9,
  nextobjectid = 30,
  properties = {
    ["music"] = "castletown"
  },
  tilesets = {
    {
      name = "castletown_inside",
      firstgid = 1,
      filename = "../tilesets/castletown_inside.tsx",
      exportfilename = "../tilesets/castletown_inside.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 39,
      height = 12,
      id = 1,
      name = "tileset",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 19, 38, 38, 38, 38, 38, 38, 38, 38, 38, 20, 38, 38, 38, 38, 38, 20, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 20, 38, 38, 0, 0, 0, 0,
        0, 0, 0, 38, 38, 23, 38, 38, 38, 38, 38, 38, 38, 21, 38, 38, 38, 38, 20, 38, 21, 38, 38, 38, 23, 38, 38, 38, 15, 11, 12, 13, 14, 38, 38, 0, 0, 0, 0,
        0, 0, 0, 38, 38, 38, 21, 38, 38, 38, 38, 38, 20, 38, 38, 38, 38, 38, 38, 38, 22, 38, 38, 38, 38, 38, 21, 38, 33, 29, 30, 31, 32, 38, 24, 0, 0, 0, 0,
        0, 0, 0, 38, 23, 38, 38, 38, 38, 38, 38, 22, 38, 38, 38, 38, 38, 38, 38, 20, 38, 38, 0, 0, 38, 20, 38, 38, 38, 47, 48, 49, 22, 38, 38, 0, 0, 0, 0,
        0, 0, 0, 58, 59, 59, 59, 59, 59, 59, 59, 59, 56, 59, 59, 59, 0, 56, 59, 59, 59, 59, 59, 59, 59, 59, 56, 59, 59, 65, 66, 67, 59, 59, 60, 0, 0, 0, 0,
        0, 0, 0, 44, 44, 8, 44, 44, 44, 8, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 8, 27, 44, 44, 44, 44, 44, 44, 9, 10, 0, 0, 0, 0,
        0, 0, 0, 44, 44, 44, 44, 26, 44, 44, 44, 9, 44, 44, 44, 8, 44, 44, 44, 8, 44, 44, 44, 44, 8, 44, 44, 44, 44, 44, 44, 27, 8, 44, 28, 0, 0, 0, 0,
        0, 0, 0, 44, 44, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 44, 9, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 27, 44, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 44, 44, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/tilesets/castletown_door_lancer.png",
      id = 4,
      name = "door_lancer",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 852,
      offsety = 88.0105,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/tilesets/castletown_door_susie.png",
      id = 2,
      name = "door_susie",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 264.667,
      offsety = 54,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/tilesets/castletown_door_kris.png",
      id = 3,
      name = "door_kris",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 589.453,
      offsety = 111.996,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 240,
          width = 80,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 1160,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1400,
          y = 240,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 200,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 200,
          width = 240,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 200,
          width = 204.5,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 955.5,
          y = 196,
          width = 225.5,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1261.33,
          y = 200,
          width = 138.667,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640.5,
          y = -639.5,
          width = 118.5,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 13,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280.667,
          y = 192,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["map"] = "map_castletown_room",
            ["marker"] = "room1",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 14,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 599.333,
          y = 190.667,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["map"] = "map_castletown_room",
            ["marker"] = "room2",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 19,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 886,
          y = 200.667,
          width = 68.6667,
          height = 30.6667,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "map_castletown_room_lancer",
            ["marker"] = "lancerroom",
            ["sound"] = "splat"
          }
        },
        {
          id = 20,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1186,
          y = 203.5,
          width = 69,
          height = 22.5,
          rotation = 0,
          visible = true,
          properties = {
            ["facing"] = "down",
            ["map"] = "map_castletown_secondfloor",
            ["marker"] = "floor2_stair",
            ["sound"] = "escaped"
          }
        },
        {
          id = 23,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 921.5,
          y = -639,
          width = 131.5,
          height = 30.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 280.333,
          y = 228,
          width = 79.6667,
          height = 6.66667,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "susie_room.transition_s"
          }
        },
        {
          id = 29,
          name = "script",
          type = "",
          shape = "rectangle",
          x = 599.75,
          y = 230.5,
          width = 79.5,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "kris_room.transition_k"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 10,
          name = "hall1",
          type = "",
          shape = "point",
          x = 320,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "hall2",
          type = "",
          shape = "point",
          x = 640,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "spawn",
          type = "",
          shape = "point",
          x = 179,
          y = 401,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "hall3",
          type = "",
          shape = "point",
          x = 920,
          y = 280,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "floor1_stair",
          type = "",
          shape = "point",
          x = 1222,
          y = 274,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
