return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 48,
  height = 36,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 21,
  nextobjectid = 272,
  properties = {
    ["border"] = "leaves",
    ["inside"] = true,
    ["light"] = true,
    ["music"] = "noelle"
  },
  tilesets = {
    {
      name = "hometownobjects",
      firstgid = 1,
      filename = "../../../../tilesets/hometownobjects.tsx",
      exportfilename = "../../../../tilesets/hometownobjects.lua"
    }
  },
  layers = {
    {
      type = "imagelayer",
      image = "../../../../../../assets/sprites/world/maps/hometown/noellehouse/noellelivingroom.png",
      id = 2,
      name = "bg",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "objects_deco",
      class = "",
      visible = true,
      opacity = 0.94,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 952,
          width = 56,
          height = 30,
          rotation = 0,
          gid = 121,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 986,
          y = 980,
          width = 98,
          height = 86,
          rotation = 0,
          gid = 80,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 638,
          y = 930,
          width = 80,
          height = 80,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 774,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 878,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 982,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1086,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1190,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1542,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 462,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 356,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 710,
          y = 584,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 608,
          y = 584,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 812,
          y = 584,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 584,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1196,
          y = 584,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1302,
          y = 584,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1174,
          y = 182,
          width = 56,
          height = 32,
          rotation = 0,
          gid = 92,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1016,
          y = 304,
          width = 74,
          height = 70,
          rotation = 0,
          gid = 88,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 726,
          y = 720,
          width = 108,
          height = 108,
          rotation = 0,
          gid = 103,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 250,
          y = 872,
          width = 14,
          height = 14,
          rotation = 0,
          gid = 102,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1158,
          y = 930,
          width = 80,
          height = 80,
          rotation = 0,
          gid = 91,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 296,
          y = 1024,
          width = 86,
          height = 52,
          rotation = 0,
          gid = 120,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1392,
          y = 1022,
          width = 86,
          height = 52,
          rotation = 0,
          gid = 120,
          visible = true,
          properties = {}
        },
        {
          id = 205,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1280,
          width = 160,
          height = 110,
          rotation = 0,
          gid = 98,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1090,
          y = 1276,
          width = 84,
          height = 102,
          rotation = 0,
          gid = 101,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 740,
          y = 1276,
          width = 84,
          height = 102,
          rotation = 0,
          gid = 100,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 244,
          name = "entrykitchen",
          type = "",
          shape = "point",
          x = 1116,
          y = 1034,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "entrycloset",
          type = "",
          shape = "point",
          x = 756,
          y = 1034,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "entrybath",
          type = "",
          shape = "point",
          x = 1320,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "entrydess",
          type = "",
          shape = "point",
          x = 880,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "entrynoelle",
          type = "",
          shape = "point",
          x = 680,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "spawn",
          type = "",
          shape = "point",
          x = 1560,
          y = 1080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 19,
      name = "objects_events",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 263,
          name = "toysanta",
          type = "",
          shape = "rectangle",
          x = 312,
          y = 902,
          width = 52,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {
            ["santa_type"] = 1
          }
        },
        {
          id = 264,
          name = "toysanta",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 902,
          width = 52,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {
            ["santa_type"] = 0
          }
        },
        {
          id = 265,
          name = "toysanta",
          type = "",
          shape = "rectangle",
          x = 935,
          y = 614,
          width = 52,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {
            ["santa_type"] = 2
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 135,
          name = "entrykitchen",
          type = "",
          shape = "point",
          x = 1116,
          y = 1034,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "entrycloset",
          type = "",
          shape = "point",
          x = 756,
          y = 1034,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "entrybath",
          type = "",
          shape = "point",
          x = 1320,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "entrydess",
          type = "",
          shape = "point",
          x = 880,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 143,
          name = "entrynoelle",
          type = "",
          shape = "point",
          x = 680,
          y = 760,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "spawn",
          type = "",
          shape = "point",
          x = 1560,
          y = 1080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects_deco2",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 1120,
          width = 290,
          height = 38,
          rotation = 0,
          gid = 113,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 350,
          y = 1120,
          width = 290,
          height = 38,
          rotation = 0,
          gid = 113,
          visible = true,
          properties = {}
        },
        {
          id = 262,
          name = "noellecouch",
          type = "",
          shape = "rectangle",
          x = 812,
          y = 1136,
          width = 292,
          height = 112,
          rotation = 0,
          gid = 99,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 39,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 862,
          y = 920,
          width = 58,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's a thermostat.)[wait:5]\n* (The only option is cold.)"
          }
        },
        {
          id = 40,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1000,
          y = 920,
          width = 58,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (The auto-treat-catcher is ready to nab anything in range.)"
          }
        },
        {
          id = 76,
          name = "interactable",
          type = "",
          shape = "polygon",
          x = 200,
          y = 1080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = -40 },
            { x = 40, y = -160 },
            { x = 0, y = -120 }
          },
          properties = {
            ["solid"] = true,
            ["text1"] = "* (The house's back door.)[wait:5]\n* (There's no need to use it.)"
          }
        },
        {
          id = 113,
          name = "transition",
          type = "",
          shape = "polygon",
          x = 1600,
          y = 1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 40 },
            { x = 40, y = 0 }
          },
          properties = {
            ["exit_delay"] = 0.2,
            ["exit_sound"] = "doorclose",
            ["facing"] = "down",
            ["map"] = "hometown/noelleyard",
            ["marker"] = "entry",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 116,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 1160,
          y = 200,
          width = 80,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's locked.)"
          }
        },
        {
          id = 134,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 960,
          width = 69.3333,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_delay"] = 0.2,
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "hometown/noellehouse/noekitchen",
            ["marker"] = "entry",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 136,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 960,
          width = 80,
          height = 39.25,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_delay"] = 0.2,
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "hometown/noellehouse/closet",
            ["marker"] = "spawn",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 139,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 680,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "hometown/noellehouse/noebathroom",
            ["marker"] = "spawn",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 141,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 840,
          y = 680,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "hometown/noellehouse/desroom",
            ["marker"] = "spawn",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 144,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 680,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["exit_sound"] = "doorclose",
            ["facing"] = "up",
            ["map"] = "hometown/noellehouse/noeroom",
            ["marker"] = "spawn",
            ["sound"] = "dooropen"
          }
        },
        {
          id = 145,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 400,
          y = 880,
          width = 79.6667,
          height = 132,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (It's a fridge containing lots of greens and bottled water.)"
          }
        },
        {
          id = 270,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 906,
          y = 1168,
          width = 94,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (Just an empty table.)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "collision",
      class = "",
      visible = true,
      opacity = 0.96,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 738,
          y = 1172,
          width = 85.3333,
          height = 104.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 1172,
          width = 85.3333,
          height = 104.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 880,
          y = 1169,
          width = 160,
          height = 111,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1320,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 1320,
          width = 320,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1178,
          y = 1320,
          width = 62,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1360,
          y = 800,
          width = 200,
          height = 218.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1221.33,
          y = 800,
          width = 58.6667,
          height = 214.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "polygon",
          x = 1560,
          y = 1000,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 40 },
            { x = 40, y = 0 }
          },
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "polygon",
          x = 1640,
          y = 1080,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = 40 },
            { x = 40, y = 0 }
          },
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 800,
          y = 840.5,
          width = 259.333,
          height = 159.25,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 840,
          width = 80,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 800,
          width = 509.5,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 800,
          width = 80,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 800,
          width = 200,
          height = 213,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "polygon",
          x = 240,
          y = 1040,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = -40 },
            { x = 0, y = -40 }
          },
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "polygon",
          x = 160,
          y = 1120,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 40, y = -40 },
            { x = 0, y = -40 }
          },
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 1120,
          width = 520,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1160,
          width = 40,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 680,
          y = 1360,
          width = 560,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1240,
          y = 1120,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 1120,
          width = 400,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1440,
          y = 520,
          width = 40,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1355.67,
          y = 520,
          width = 84.3333,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 520,
          width = 128,
          height = 212.667,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 520,
          width = 40,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1248,
          y = 520,
          width = 40,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1060,
          y = 840,
          width = 20,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 560,
          y = 520,
          width = 80,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 720,
          y = 520,
          width = 120,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 520,
          y = 720,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 920,
          y = 520,
          width = 77,
          height = 210,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 200,
          width = 40,
          height = 320,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1001,
          y = 236,
          width = 87,
          height = 95,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1091,
          y = 160,
          width = 189,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1080,
          y = 400,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1149.33,
          y = 800,
          width = 72,
          height = 200,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1120,
          y = 400,
          width = 160,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 320,
          width = 40,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 257,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1600,
          y = 1000,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 258,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1640,
          y = 1040,
          width = 40,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 259,
          name = "",
          type = "",
          shape = "rectangle",
          x = 572,
          y = 600,
          width = 54,
          height = 138,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 266,
          name = "",
          type = "",
          shape = "rectangle",
          x = 818,
          y = 1082,
          width = 276,
          height = 42,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 267,
          name = "",
          type = "",
          shape = "polygon",
          x = 1050,
          y = 1052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 40 },
            { x = 40, y = 40 }
          },
          properties = {}
        },
        {
          id = 268,
          name = "",
          type = "",
          shape = "polygon",
          x = 864,
          y = 1052,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = 40 },
            { x = -40, y = 40 }
          },
          properties = {}
        },
        {
          id = 269,
          name = "",
          type = "",
          shape = "rectangle",
          x = 864,
          y = 1052,
          width = 186,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
